version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 20
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
